### PR TITLE
Transpose ES5 => ES6

### LINKED ISSUE #3: Transpile ES5 to ES6
Currently, [source code](https://github.com/ozdemirburak/morsify/blob/master/src/morsify.js) is outdated. It would be great if we turn it to ES6. 

Hint: You may check online tools like Lebab.

### PR DESCRIPTION
**Pull request by jamesjpk123**
Fixes #3

### CODE REVIEW

**Comment by jamesjpk123** [comment]
It looks like the build with this PR fails unexpectedly. I don't know why. I'm going to try some local testing.

**Comment by ozdemirburak** [comment]
Hello James!

Thanks for your pull request. It would be great if you can check tests and update if needed, as you can see the error log from the details.

```
./src/morsify.js: line 1, col 1, Use the function form of "use strict".
./src/morsify.js: line 3, col 70, Invalid typeof value 'symbol'
./src/morsify.js: line 13, col 38, Unmatched '{'.
```

Also, you may use [arrow functions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions) and replace `var` declarations with [const or let](https://medium.com/javascript-scene/javascript-es6-var-let-or-const-ba58b8dcde75).

Thank you.

**Comment by jamesjpk123** [comment]
I’m heading out soon, but I will fix these issues ASAP!

**Comment by ozdemirburak** [comment]
It is OK, thank you :)

**Comment by jamesjpk123** [comment]
I was wondering, where are you finding this additional error information?

**Comment by jamesjpk123** [comment]
Ok, Travis CI build is passing! I'll go add some arrow functions! (also, I'm not sure if any of the variables are changed globally, or need to be changed at all. Which ones should be const vs let?)

**Comment by jamesjpk123** [comment]
I reverted what I did because they were throwing errors. I don't know much about arrow functions, but I'll research them later when I have the time so I can help convert some of the functions. Tests should be passing now.

**Comment by ozdemirburak** [comment]
What you changed was OK actually, you need to make those changes again, however, you also need to configure the project so that it will pass the tests.

See this log line for instance.

```
./src/morsify.js: line 12, col 3, 'const' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).
```

You need to declare that you are using ES6, to do that, add a [JSHint](http://jshint.com/docs/) file, `.jshintrc`, with the contents o

```
{  
  "esversion": 6 
}
```

**Comment by ozdemirburak** [comment]
Sorry James, someone has done all the changes [here](https://github.com/ozdemirburak/morsify/pull/8) before you, thank you for all of your efforts.

**Comment by jamesjpk123** [comment]
Glad that it worked out!

**Pull request closed without merging**
